---
collections:
  - name: sample.sample_collection
    version: '0.0.5'
    source: 'https://hub-galaxy-ansible-automation-platform.xxxxxx.hkg02.containers.appdomain.cloud/api/galaxy/content/published/'
  - name: bay.automation
    version: '1.0.1'
    source: 'https://hub-galaxy-ansible-automation-platform.xxxxxxxxxx.containers.appdomain.cloud/api/galaxy/content/published/'
  - name: community.vmware
